### ISSUE TITLE
how to change language

### ISSUE THREAD

**Issue by lele344** [pivattogui/bongo-gpt#1]
thank you for sharing your code.
I just have a favor to ask you, everything works but it answers me in Portuguese.
how can i change the response language of gpt?
I tried telling it to answer in my language and it replies that it does, but after I ask another question it always replies me in Portuguese.

thank you

**Comment by pivattogui** [comment]
In this project there is no way to change the language so far, but if you start the conversation in another language, it responds in the typed language.

Thanks for the issue, I will add the multi language option in the future.

**Comment by pivattogui** [comment]
[update]: Bongo-GPT now supports multi languages

**Comment by lele344** [comment]
> [update]: Bongo-GPT now supports multi languages

Thank you for your effort and your reply.
